/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hellojni2_HelloJNI2 */

#ifndef _Included_hellojni2_HelloJNI2
#define _Included_hellojni2_HelloJNI2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hellojni2_HelloJNI2
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hellojni2_HelloJNI2_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
